### ISSUE TITLE
Course file not found

### ISSUE THREAD

**Issue by FredericLeRoux** [dEAduction/dEAduction#72] opened 2021-04-16 08:03 UTC
### Bug description
The bug happens In the dialogbox to choose course and exercise. If we choose a course in the list, and the course file has been moved or deleted, deaduction does not find it.

### How to reproduce the bug
Choose a course and exercise, and start the proof.
Then quit deaduction, change the name of the course file you have just use.
Start deaduction and try to select the same course in the course list.

### Environment
This is independant of the environment.

### Fix ideas
Deaduction should check if the files still exist, and display a warning next to the name if not.
(This is better than removing the name from the list, because it helps user to find the file by providing the file name information).

### Submission checklist

1. [x] d∃∀duction is up-to-date and this bug is in the latest version.
2. [x] I've checked that no-one reported this problem by browsing [other
   issues](https://github.com/dEAduction/dEAduction/issues).
3. [x] This issue deals with one and only one issue (if you have multiple
   issues, please open multiple issues).
4. [x] I correctly labeled my issue (see commented rules below).
5. [ ] I want to fix this bug. (Check if you do, no judgement if you do not!)

**Comment by kryzar** [comment] 2021-04-16 11:32
This is duplicate of #67, I close the issue.

**Closed as completed by kryzar** 2021-04-16 11:32 UTC
Labels: type::bug, area::code, status::duplicate
